import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

st.title("📈 Stock Market Price Forecasting")

st.info("⚠️ This prediction is generated by a machine learning model for educational purposes only. It is not financial advice.")

stock = st.text_input("Enter Stock Symbol", "TCS.NS")

start_date = st.date_input(
    "Select Start Date",
    pd.to_datetime("2020-01-01")
)

if st.button("Predict"):

    data = yf.download(
        stock,
        start=start_date,
        end="2026-01-01",
        auto_adjust=False
    )

    data = data[["Open", "High", "Low", "Close", "Volume"]]
    data = data.dropna()

    # Features
    data["Previous_Close"] = data["Close"].shift(1)
    data["MA5"] = data["Close"].rolling(5).mean()
    data["MA20"] = data["Close"].rolling(20).mean()

    # Target
    data["Target"] = data["Close"].shift(-1)

    data = data.dropna()

    features = [
        "Open",
        "High",
        "Low",
        "Close",
        "Volume",
        "Previous_Close",
        "MA5",
        "MA20"
    ]

    X = data[features]
    y = data["Target"]

    # Train model
    split = int(len(data) * 0.8)

    X_train = X.iloc[:split]
    y_train = y.iloc[:split]

    model = RandomForestRegressor(
        n_estimators=200,
        random_state=42
    )

    model.fit(X_train, y_train)

    # Predict next price
    latest_data = data[features].iloc[-1:]
    next_price = model.predict(latest_data)[0]

    st.subheader("Prediction Result")

    latest_price = float(np.array(data["Close"].iloc[-1]).flatten()[0])

    col1, col2 = st.columns(2)

with col1:
    st.metric("Latest Price", f"₹{latest_price:.2f}")

with col2:
    st.metric("Predicted Price", f"₹{next_price:.2f}")
    st.subheader("Stock Price History")

chart_data = data["Close"]

if isinstance(chart_data, pd.DataFrame):
    chart_data = chart_data.iloc[:, 0]

st.line_chart(chart_data)
st.subheader("Actual vs Predicted Price")

X_test = X.iloc[split:]
y_test = y.iloc[split:]

predictions = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Price": np.array(y_test).flatten(),
    "Predicted Price": np.array(predictions).flatten()
})

st.line_chart(comparison)
mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))

st.subheader("Model Performance")

st.write("MAE:", round(mae, 2))
st.write("RMSE:", round(rmse, 2))
st.subheader("Prediction Summary")

latest_price = float(np.array(data["Close"].iloc[-1]).flatten()[0])
predicted_price = float(next_price)

st.write("Latest Price:", f"₹{latest_price:.2f}")
st.write("Predicted Next Price:", f"₹{predicted_price:.2f}")

if predicted_price > latest_price:
    st.success("📈 Model predicts a possible increase")
elif predicted_price < latest_price:
    st.warning("📉 Model predicts a possible decrease")
else:
    st.info("➡️ Model predicts a similar price")
    st.subheader("Latest Stock Data")

latest_table = data[[
    "Open",
    "High",
    "Low",
    "Close",
    "Volume"
]].tail(1)

st.dataframe(latest_table)
st.subheader("Feature Importance")

importance = pd.DataFrame({
    "Feature": features,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    "Importance",
    ascending=False
)

st.bar_chart(
    importance.set_index("Feature")
)
report = pd.DataFrame({
    "Stock": [stock],
    "Latest Price": [latest_price],
    "Predicted Price": [next_price],
    "MAE": [mae],
    "RMSE": [rmse]
})

csv = report.to_csv(index=False)

st.download_button(
    label="📥 Download Prediction Report",
    data=csv,
    file_name="stock_prediction_report.csv",
    mime="text/csv"
)